name: Publish haakco/postfix-relay Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1'

jobs:
  push_to_registry:
    name: Push Docker image haakco/postfix-relay to Docker Hub
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: haakco/postfix-relay
          tags: |
            type=raw,value={{branch}}-{{sha}}
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          build-args: |
            BASE_IMAGE_NAME=alpine
            BASE_IMAGE_TAG=latest
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
