---
name: Publish ghcr.io/ghcr.io/haakco/postfix-relay Docker image
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1'

permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image ghcr.io/haakco/postfix-relay to Docker Hub
    runs-on: "self-hosted"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/haakco/postfix-relay
          tags: |
            type=raw,value={{branch}}-{{sha}}
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/haakco
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_NAME=alpine
            BASE_IMAGE_TAG=latest
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/haakco/postfix-relay:buildcache
          cache-to: type=registry,ref=ghcr.io/haakco/postfix-relay:buildcache,mode=max
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
